local default = {}

default.colorscheme = require("core.colorscheme")["tokyonight"]

default.keymap = require "core.keymap"

default.symbols = {
    Affirmative = "✓ ",
    Array = " ",
    Boolean = " ",
    Class = "󰠱 ",
    CodeAction = " ",
    Color = "󰏘 ",
    Component = "󰡀 ",
    Constant = "󰏿 ",
    Constructor = " ",
    Definition = " ",
    Diagnostic = " ",
    Dice1 = "󰇊 ",
    Dice2 = "󰇋 ",
    Dice3 = "󰇌 ",
    Dice4 = "󰇍 ",
    Dice5 = "󰇎 ",
    Dice6 = "󰇏 ",
    Dos = " ",
    Enum = " ",
    EnumMember = " ",
    Error = " ",
    Event = " ",
    Field = "󰜢 ",
    File = "󰈙 ",
    Folder = "󰉋 ",
    Fragment = " ",
    Function = "󰊕 ",
    Hint = " ",
    Info = " ",
    Interface = " ",
    Key = " ",
    Keyword = "󰌋 ",
    LspSagaFinder = " ",
    Mac = " ",
    Method = "󰆧 ",
    Module = "󰆧 ",
    Namespace = " ",
    Negative = "✗ ",
    Null = "󰟢 ",
    Number = " ",
    Object = " ",
    Operator = "󰆕 ",
    Package = " ",
    Pending = "➜ ",
    Property = "󰜢 ",
    Reference = "󰈇 ",
    RenamePrompt = "➤ ",
    Snippet = " ",
    String = " ",
    Struct = "󰙅 ",
    Text = "󰉿 ",
    TypeParameter = "󰉺 ",
    Unit = "󰑭 ",
    Unix = " ",
    Value = "󰎠 ",
    Variable = "󰀫 ",
    Warn = " ",
}

default.plugin = {
    config = require "plugins.config",
    keymap = require "plugins.keymap",
    lazy = require "plugins.lazy",
    list = require "plugins.list",
}

default.lsp = {
    ensure_installed = {
        "clangd",
        "cssls",
        "denols",
        "emmet_ls",
        "html",
        "jsonls",
        "lua_ls",
        "omnisharp",
        "pyright",
        "tsserver",
    },
    keymap = require "lsp.keymap",
    null_ls_sources = function(formatting, _, _)
        return {
            formatting.shfmt,
            formatting.stylua,
            formatting.csharpier,
            formatting.prettier.with {
                filetypes = {
                    "javascript",
                    "javascriptreact",
                    "typescript",
                    "typescriptreact",
                    "vue",
                    "css",
                    "scss",
                    "less",
                    "html",
                    "json",
                    "yaml",
                    "graphql",
                },
                extra_filetypes = { "njk" },
                prefer_local = "node_modules/.bin",
            },
            formatting.autopep8,
        }
    end,
    -- Do not configure dartls here when using flutter-tools
    servers = {
        clangd = "",
        cssls = "",
        denols = "",
        emmet_ls = "",
        html = "",
        jsonls = "",
        lua_ls = "",
        omnisharp = "",
        pyright = "",
        tsserver = "",
    },
}

return default
